//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Assets/Scripts/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Left"",
            ""id"": ""46a371d0-254f-4988-beed-460e467dac88"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""41971d71-d468-41b8-825a-03abce2e5813"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Value"",
                    ""id"": ""7f0f799f-121f-432c-81b4-6a68c7306898"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Strike"",
                    ""type"": ""Value"",
                    ""id"": ""b04af50e-e8b3-4ac2-abf2-f7e4b9381328"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClawSwap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4831c4ec-e298-46bc-83a0-beae057d56de"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c28312aa-db89-453b-807b-e285d3c0074e"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""833b9d1c-0551-4cd3-8962-f030c125c57e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""abd058b4-3aae-465c-a3c0-b04abfea95f3"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9865f50a-c6e3-48dd-8b25-ca74636bb99d"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8ad0a4bb-c604-4969-b3ca-50d6bc45b3a5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c6daea5-1f3e-42e9-a354-5d32385948d3"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Strike"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7430ac20-3feb-4d23-a1b9-225f99db75f3"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""ClawSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f2a40f61-dd2a-4e80-a411-29f6e07e0896"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwap"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a3701c36-ffcb-4b08-a31b-f76d07853e09"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""ClawSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d08fba8a-1304-4573-8a9c-6c0a3f69d411"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""ClawSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1a70d311-93d9-41d7-9c3d-ef573e870b39"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwap"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de1fa178-0bef-4a33-901f-99a448738af0"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Right"",
            ""id"": ""7aa9b8a9-6820-42fb-993a-3008a4fdec66"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5325d756-e813-4131-a5e4-0013d10b7fed"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Value"",
                    ""id"": ""29402ad7-a225-4821-bf8b-474ded42a319"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Strike"",
                    ""type"": ""Value"",
                    ""id"": ""3d7aa770-aa63-4cb8-8ff4-fae80128fe5c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClawSwap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""415575e9-ebfb-4cd3-bcd3-df1e863516eb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8c556158-c155-4bf9-a0e9-bd7415577d5a"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""ClawSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""3a1a41b8-f32c-4049-9dfd-cfdceb70a1ff"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwap"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6503a7de-8778-4f41-b845-93c5d6b5e60c"",
                    ""path"": ""<XInputController>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""ClawSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c226e504-8f8d-48f8-bbad-06be5a1c62e2"",
                    ""path"": ""<XInputController>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""ClawSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9433cf70-55c0-4dee-abbe-d8b634839000"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8a5513d9-e224-4920-8eb1-70f772ac51d2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""71ede45b-e280-4e25-918d-c4320f92f520"",
                    ""path"": ""<XInputController>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""195af253-24f3-4d5b-9461-18fd6a037ed0"",
                    ""path"": ""<XInputController>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ce864ce0-4d56-4324-b52c-341a61dec0f5"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Controller"",
                    ""action"": ""Strike"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44fb8b30-77f7-45cd-a643-edb98d6a52e0"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""AllP1"",
            ""id"": ""84283639-6ead-4afd-ad90-a9166f90a000"",
            ""actions"": [
                {
                    ""name"": ""ClawSwapRight"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ba10054b-3426-47e5-aa79-7362adf277f1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClawSwapLeft"",
                    ""type"": ""PassThrough"",
                    ""id"": ""48c74243-f386-413a-a5ad-627929879d53"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StrikeLeft"",
                    ""type"": ""Value"",
                    ""id"": ""ded36d76-4809-4407-a59f-ba4327de37ed"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JumpLeft"",
                    ""type"": ""Value"",
                    ""id"": ""402bd26d-7bb0-477a-9ae1-0e23d52422c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""PassThrough"",
                    ""id"": ""94e98eb2-9426-42d2-bf34-cb6abbd8367b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StrikeRight"",
                    ""type"": ""Value"",
                    ""id"": ""42580470-9b0a-44b1-a0e3-c6907f7caf45"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JumpRight"",
                    ""type"": ""Value"",
                    ""id"": ""8a646065-cb78-411c-a4c3-d88039c07141"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""PassThrough"",
                    ""id"": ""312a9d87-8a5a-4540-b9b1-35f674b41c51"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""38cf2ca9-a1f0-4781-b8d7-6c1d9270fc2b"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ee343221-f315-480e-9408-5d882ea663bb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e44e9a03-e724-42d9-a877-0e83f5f9c458"",
                    ""path"": ""<XInputController>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""61c82364-055a-44b4-a654-d1f98f9a2306"",
                    ""path"": ""<XInputController>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""70f8ff82-0b44-4d92-8c9a-bcc43d272176"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StrikeRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8689e28f-5345-4f95-8c12-5c47cc8faaeb"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""386a4766-6e99-4139-bf22-b7ea58dad5d3"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""37e7d0fd-90ad-4980-b8f0-48e1b57585ac"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3b2dfd24-4106-4e75-a733-a0f5b602d6cc"",
                    ""path"": ""<XInputController>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9a558e64-d594-4e60-90b5-8a5082090aac"",
                    ""path"": ""<XInputController>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0e1dd476-67a4-4f22-a939-9c073eddbe67"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4cfe82ec-1b86-4040-88ff-7f690016106d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""92d40629-5bf5-47bf-a7c9-ef873939bb7e"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9c2099ec-b4f6-4467-9d73-e0273514c396"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e08c6ce5-73b8-4d05-903d-a19b2c5a8084"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08d48d0a-8c75-4fea-96df-31cbf85a6864"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StrikeLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""930ef5eb-bcc6-4d4e-9719-9598dcec9bc7"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""36ae8ead-04d9-4cdc-8371-af62484124c6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ebcc5981-1a2e-412f-b28a-0b24c9b09a11"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c62b1e9e-aac3-437d-8e26-fc8bff581222"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""AllP2"",
            ""id"": ""7552eb30-6087-41fb-98c9-02b5b586a9b6"",
            ""actions"": [
                {
                    ""name"": ""ClawSwapLeft"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8de0c1d9-f3f8-482f-a497-33b451162e65"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClawSwapRight"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a807c8bb-6a8f-4996-90b8-662b4644ce4a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StrikeRight"",
                    ""type"": ""Value"",
                    ""id"": ""b6d6cac1-1fc0-41c5-9bcd-a32395f18a8a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JumpRight"",
                    ""type"": ""Value"",
                    ""id"": ""75cedada-b652-45eb-851d-edc8be64f459"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f4df509b-fa6c-48d6-a751-fed37acb0035"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StrikeLeft"",
                    ""type"": ""Value"",
                    ""id"": ""c494d305-c841-48ce-9304-63f6b03fbba4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JumpLeft"",
                    ""type"": ""Value"",
                    ""id"": ""38ab4618-67ac-4afd-82f0-569661a3cb72"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""PassThrough"",
                    ""id"": ""45515b93-0e9a-4c27-b165-cc154d769dfd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c94f9f09-94f5-410d-86be-3dbb6eb2f971"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""30c9f327-e57c-49e2-98d9-ef9d7baf4320"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6c5e0017-4c8a-4054-85e0-369646e6dcd2"",
                    ""path"": ""<XInputController>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6a2d84b5-eabc-4578-8813-6232c5701dc8"",
                    ""path"": ""<XInputController>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""906f37bf-1608-4164-9efd-891a020efb20"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StrikeLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a047453-42cf-42c6-bb58-e2aa79ab0ce9"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59c98c6e-3f59-4f14-a8bb-d07cf3ef8814"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5874f9a3-2a66-41a8-b523-089a9510b53d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f4725860-a3d1-49b1-ab85-8b3f007412b4"",
                    ""path"": ""<XInputController>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""df607b05-d0f3-433e-b2e0-7381a6f10aaf"",
                    ""path"": ""<XInputController>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""85f66502-ef3a-4f49-9b6d-643177a71935"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f985821d-46eb-4475-aa4e-61eaf57e4d05"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""65781d04-5797-4f9d-b288-ae1210f6fc2e"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""89f81969-8352-40c9-a8af-10e5ec14eb55"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c55c5d10-02d8-4240-b477-89a92cffa1c0"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3fb531e-6257-4e23-8b6b-3f189cd1cde0"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StrikeRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d938c1c-e2a4-4a3f-ab38-0aaa38419941"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2b55a9f3-6db9-4b4d-b353-643c13a45611"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a00fc49d-8441-4314-aaf5-e13db2e4f40b"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""583b0651-0fb3-452d-9ac6-9d0d30e6e00c"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClawSwapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Xbox Controller"",
            ""bindingGroup"": ""Xbox Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Left
        m_Left = asset.FindActionMap("Left", throwIfNotFound: true);
        m_Left_Move = m_Left.FindAction("Move", throwIfNotFound: true);
        m_Left_Jump = m_Left.FindAction("Jump", throwIfNotFound: true);
        m_Left_Strike = m_Left.FindAction("Strike", throwIfNotFound: true);
        m_Left_ClawSwap = m_Left.FindAction("ClawSwap", throwIfNotFound: true);
        // Right
        m_Right = asset.FindActionMap("Right", throwIfNotFound: true);
        m_Right_Move = m_Right.FindAction("Move", throwIfNotFound: true);
        m_Right_Jump = m_Right.FindAction("Jump", throwIfNotFound: true);
        m_Right_Strike = m_Right.FindAction("Strike", throwIfNotFound: true);
        m_Right_ClawSwap = m_Right.FindAction("ClawSwap", throwIfNotFound: true);
        // AllP1
        m_AllP1 = asset.FindActionMap("AllP1", throwIfNotFound: true);
        m_AllP1_ClawSwapRight = m_AllP1.FindAction("ClawSwapRight", throwIfNotFound: true);
        m_AllP1_ClawSwapLeft = m_AllP1.FindAction("ClawSwapLeft", throwIfNotFound: true);
        m_AllP1_StrikeLeft = m_AllP1.FindAction("StrikeLeft", throwIfNotFound: true);
        m_AllP1_JumpLeft = m_AllP1.FindAction("JumpLeft", throwIfNotFound: true);
        m_AllP1_MoveLeft = m_AllP1.FindAction("MoveLeft", throwIfNotFound: true);
        m_AllP1_StrikeRight = m_AllP1.FindAction("StrikeRight", throwIfNotFound: true);
        m_AllP1_JumpRight = m_AllP1.FindAction("JumpRight", throwIfNotFound: true);
        m_AllP1_MoveRight = m_AllP1.FindAction("MoveRight", throwIfNotFound: true);
        // AllP2
        m_AllP2 = asset.FindActionMap("AllP2", throwIfNotFound: true);
        m_AllP2_ClawSwapLeft = m_AllP2.FindAction("ClawSwapLeft", throwIfNotFound: true);
        m_AllP2_ClawSwapRight = m_AllP2.FindAction("ClawSwapRight", throwIfNotFound: true);
        m_AllP2_StrikeRight = m_AllP2.FindAction("StrikeRight", throwIfNotFound: true);
        m_AllP2_JumpRight = m_AllP2.FindAction("JumpRight", throwIfNotFound: true);
        m_AllP2_MoveRight = m_AllP2.FindAction("MoveRight", throwIfNotFound: true);
        m_AllP2_StrikeLeft = m_AllP2.FindAction("StrikeLeft", throwIfNotFound: true);
        m_AllP2_JumpLeft = m_AllP2.FindAction("JumpLeft", throwIfNotFound: true);
        m_AllP2_MoveLeft = m_AllP2.FindAction("MoveLeft", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Left
    private readonly InputActionMap m_Left;
    private ILeftActions m_LeftActionsCallbackInterface;
    private readonly InputAction m_Left_Move;
    private readonly InputAction m_Left_Jump;
    private readonly InputAction m_Left_Strike;
    private readonly InputAction m_Left_ClawSwap;
    public struct LeftActions
    {
        private @PlayerControls m_Wrapper;
        public LeftActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Left_Move;
        public InputAction @Jump => m_Wrapper.m_Left_Jump;
        public InputAction @Strike => m_Wrapper.m_Left_Strike;
        public InputAction @ClawSwap => m_Wrapper.m_Left_ClawSwap;
        public InputActionMap Get() { return m_Wrapper.m_Left; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LeftActions set) { return set.Get(); }
        public void SetCallbacks(ILeftActions instance)
        {
            if (m_Wrapper.m_LeftActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_LeftActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_LeftActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_LeftActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_LeftActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_LeftActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_LeftActionsCallbackInterface.OnJump;
                @Strike.started -= m_Wrapper.m_LeftActionsCallbackInterface.OnStrike;
                @Strike.performed -= m_Wrapper.m_LeftActionsCallbackInterface.OnStrike;
                @Strike.canceled -= m_Wrapper.m_LeftActionsCallbackInterface.OnStrike;
                @ClawSwap.started -= m_Wrapper.m_LeftActionsCallbackInterface.OnClawSwap;
                @ClawSwap.performed -= m_Wrapper.m_LeftActionsCallbackInterface.OnClawSwap;
                @ClawSwap.canceled -= m_Wrapper.m_LeftActionsCallbackInterface.OnClawSwap;
            }
            m_Wrapper.m_LeftActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Strike.started += instance.OnStrike;
                @Strike.performed += instance.OnStrike;
                @Strike.canceled += instance.OnStrike;
                @ClawSwap.started += instance.OnClawSwap;
                @ClawSwap.performed += instance.OnClawSwap;
                @ClawSwap.canceled += instance.OnClawSwap;
            }
        }
    }
    public LeftActions @Left => new LeftActions(this);

    // Right
    private readonly InputActionMap m_Right;
    private IRightActions m_RightActionsCallbackInterface;
    private readonly InputAction m_Right_Move;
    private readonly InputAction m_Right_Jump;
    private readonly InputAction m_Right_Strike;
    private readonly InputAction m_Right_ClawSwap;
    public struct RightActions
    {
        private @PlayerControls m_Wrapper;
        public RightActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Right_Move;
        public InputAction @Jump => m_Wrapper.m_Right_Jump;
        public InputAction @Strike => m_Wrapper.m_Right_Strike;
        public InputAction @ClawSwap => m_Wrapper.m_Right_ClawSwap;
        public InputActionMap Get() { return m_Wrapper.m_Right; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RightActions set) { return set.Get(); }
        public void SetCallbacks(IRightActions instance)
        {
            if (m_Wrapper.m_RightActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_RightActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_RightActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_RightActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_RightActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_RightActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_RightActionsCallbackInterface.OnJump;
                @Strike.started -= m_Wrapper.m_RightActionsCallbackInterface.OnStrike;
                @Strike.performed -= m_Wrapper.m_RightActionsCallbackInterface.OnStrike;
                @Strike.canceled -= m_Wrapper.m_RightActionsCallbackInterface.OnStrike;
                @ClawSwap.started -= m_Wrapper.m_RightActionsCallbackInterface.OnClawSwap;
                @ClawSwap.performed -= m_Wrapper.m_RightActionsCallbackInterface.OnClawSwap;
                @ClawSwap.canceled -= m_Wrapper.m_RightActionsCallbackInterface.OnClawSwap;
            }
            m_Wrapper.m_RightActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Strike.started += instance.OnStrike;
                @Strike.performed += instance.OnStrike;
                @Strike.canceled += instance.OnStrike;
                @ClawSwap.started += instance.OnClawSwap;
                @ClawSwap.performed += instance.OnClawSwap;
                @ClawSwap.canceled += instance.OnClawSwap;
            }
        }
    }
    public RightActions @Right => new RightActions(this);

    // AllP1
    private readonly InputActionMap m_AllP1;
    private IAllP1Actions m_AllP1ActionsCallbackInterface;
    private readonly InputAction m_AllP1_ClawSwapRight;
    private readonly InputAction m_AllP1_ClawSwapLeft;
    private readonly InputAction m_AllP1_StrikeLeft;
    private readonly InputAction m_AllP1_JumpLeft;
    private readonly InputAction m_AllP1_MoveLeft;
    private readonly InputAction m_AllP1_StrikeRight;
    private readonly InputAction m_AllP1_JumpRight;
    private readonly InputAction m_AllP1_MoveRight;
    public struct AllP1Actions
    {
        private @PlayerControls m_Wrapper;
        public AllP1Actions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClawSwapRight => m_Wrapper.m_AllP1_ClawSwapRight;
        public InputAction @ClawSwapLeft => m_Wrapper.m_AllP1_ClawSwapLeft;
        public InputAction @StrikeLeft => m_Wrapper.m_AllP1_StrikeLeft;
        public InputAction @JumpLeft => m_Wrapper.m_AllP1_JumpLeft;
        public InputAction @MoveLeft => m_Wrapper.m_AllP1_MoveLeft;
        public InputAction @StrikeRight => m_Wrapper.m_AllP1_StrikeRight;
        public InputAction @JumpRight => m_Wrapper.m_AllP1_JumpRight;
        public InputAction @MoveRight => m_Wrapper.m_AllP1_MoveRight;
        public InputActionMap Get() { return m_Wrapper.m_AllP1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AllP1Actions set) { return set.Get(); }
        public void SetCallbacks(IAllP1Actions instance)
        {
            if (m_Wrapper.m_AllP1ActionsCallbackInterface != null)
            {
                @ClawSwapRight.started -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnClawSwapRight;
                @ClawSwapRight.performed -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnClawSwapRight;
                @ClawSwapRight.canceled -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnClawSwapRight;
                @ClawSwapLeft.started -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnClawSwapLeft;
                @ClawSwapLeft.performed -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnClawSwapLeft;
                @ClawSwapLeft.canceled -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnClawSwapLeft;
                @StrikeLeft.started -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnStrikeLeft;
                @StrikeLeft.performed -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnStrikeLeft;
                @StrikeLeft.canceled -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnStrikeLeft;
                @JumpLeft.started -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnJumpLeft;
                @JumpLeft.performed -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnJumpLeft;
                @JumpLeft.canceled -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnJumpLeft;
                @MoveLeft.started -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.performed -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.canceled -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnMoveLeft;
                @StrikeRight.started -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnStrikeRight;
                @StrikeRight.performed -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnStrikeRight;
                @StrikeRight.canceled -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnStrikeRight;
                @JumpRight.started -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnJumpRight;
                @JumpRight.performed -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnJumpRight;
                @JumpRight.canceled -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnJumpRight;
                @MoveRight.started -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnMoveRight;
                @MoveRight.performed -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnMoveRight;
                @MoveRight.canceled -= m_Wrapper.m_AllP1ActionsCallbackInterface.OnMoveRight;
            }
            m_Wrapper.m_AllP1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ClawSwapRight.started += instance.OnClawSwapRight;
                @ClawSwapRight.performed += instance.OnClawSwapRight;
                @ClawSwapRight.canceled += instance.OnClawSwapRight;
                @ClawSwapLeft.started += instance.OnClawSwapLeft;
                @ClawSwapLeft.performed += instance.OnClawSwapLeft;
                @ClawSwapLeft.canceled += instance.OnClawSwapLeft;
                @StrikeLeft.started += instance.OnStrikeLeft;
                @StrikeLeft.performed += instance.OnStrikeLeft;
                @StrikeLeft.canceled += instance.OnStrikeLeft;
                @JumpLeft.started += instance.OnJumpLeft;
                @JumpLeft.performed += instance.OnJumpLeft;
                @JumpLeft.canceled += instance.OnJumpLeft;
                @MoveLeft.started += instance.OnMoveLeft;
                @MoveLeft.performed += instance.OnMoveLeft;
                @MoveLeft.canceled += instance.OnMoveLeft;
                @StrikeRight.started += instance.OnStrikeRight;
                @StrikeRight.performed += instance.OnStrikeRight;
                @StrikeRight.canceled += instance.OnStrikeRight;
                @JumpRight.started += instance.OnJumpRight;
                @JumpRight.performed += instance.OnJumpRight;
                @JumpRight.canceled += instance.OnJumpRight;
                @MoveRight.started += instance.OnMoveRight;
                @MoveRight.performed += instance.OnMoveRight;
                @MoveRight.canceled += instance.OnMoveRight;
            }
        }
    }
    public AllP1Actions @AllP1 => new AllP1Actions(this);

    // AllP2
    private readonly InputActionMap m_AllP2;
    private IAllP2Actions m_AllP2ActionsCallbackInterface;
    private readonly InputAction m_AllP2_ClawSwapLeft;
    private readonly InputAction m_AllP2_ClawSwapRight;
    private readonly InputAction m_AllP2_StrikeRight;
    private readonly InputAction m_AllP2_JumpRight;
    private readonly InputAction m_AllP2_MoveRight;
    private readonly InputAction m_AllP2_StrikeLeft;
    private readonly InputAction m_AllP2_JumpLeft;
    private readonly InputAction m_AllP2_MoveLeft;
    public struct AllP2Actions
    {
        private @PlayerControls m_Wrapper;
        public AllP2Actions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClawSwapLeft => m_Wrapper.m_AllP2_ClawSwapLeft;
        public InputAction @ClawSwapRight => m_Wrapper.m_AllP2_ClawSwapRight;
        public InputAction @StrikeRight => m_Wrapper.m_AllP2_StrikeRight;
        public InputAction @JumpRight => m_Wrapper.m_AllP2_JumpRight;
        public InputAction @MoveRight => m_Wrapper.m_AllP2_MoveRight;
        public InputAction @StrikeLeft => m_Wrapper.m_AllP2_StrikeLeft;
        public InputAction @JumpLeft => m_Wrapper.m_AllP2_JumpLeft;
        public InputAction @MoveLeft => m_Wrapper.m_AllP2_MoveLeft;
        public InputActionMap Get() { return m_Wrapper.m_AllP2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AllP2Actions set) { return set.Get(); }
        public void SetCallbacks(IAllP2Actions instance)
        {
            if (m_Wrapper.m_AllP2ActionsCallbackInterface != null)
            {
                @ClawSwapLeft.started -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnClawSwapLeft;
                @ClawSwapLeft.performed -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnClawSwapLeft;
                @ClawSwapLeft.canceled -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnClawSwapLeft;
                @ClawSwapRight.started -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnClawSwapRight;
                @ClawSwapRight.performed -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnClawSwapRight;
                @ClawSwapRight.canceled -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnClawSwapRight;
                @StrikeRight.started -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnStrikeRight;
                @StrikeRight.performed -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnStrikeRight;
                @StrikeRight.canceled -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnStrikeRight;
                @JumpRight.started -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnJumpRight;
                @JumpRight.performed -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnJumpRight;
                @JumpRight.canceled -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnJumpRight;
                @MoveRight.started -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnMoveRight;
                @MoveRight.performed -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnMoveRight;
                @MoveRight.canceled -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnMoveRight;
                @StrikeLeft.started -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnStrikeLeft;
                @StrikeLeft.performed -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnStrikeLeft;
                @StrikeLeft.canceled -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnStrikeLeft;
                @JumpLeft.started -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnJumpLeft;
                @JumpLeft.performed -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnJumpLeft;
                @JumpLeft.canceled -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnJumpLeft;
                @MoveLeft.started -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.performed -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.canceled -= m_Wrapper.m_AllP2ActionsCallbackInterface.OnMoveLeft;
            }
            m_Wrapper.m_AllP2ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ClawSwapLeft.started += instance.OnClawSwapLeft;
                @ClawSwapLeft.performed += instance.OnClawSwapLeft;
                @ClawSwapLeft.canceled += instance.OnClawSwapLeft;
                @ClawSwapRight.started += instance.OnClawSwapRight;
                @ClawSwapRight.performed += instance.OnClawSwapRight;
                @ClawSwapRight.canceled += instance.OnClawSwapRight;
                @StrikeRight.started += instance.OnStrikeRight;
                @StrikeRight.performed += instance.OnStrikeRight;
                @StrikeRight.canceled += instance.OnStrikeRight;
                @JumpRight.started += instance.OnJumpRight;
                @JumpRight.performed += instance.OnJumpRight;
                @JumpRight.canceled += instance.OnJumpRight;
                @MoveRight.started += instance.OnMoveRight;
                @MoveRight.performed += instance.OnMoveRight;
                @MoveRight.canceled += instance.OnMoveRight;
                @StrikeLeft.started += instance.OnStrikeLeft;
                @StrikeLeft.performed += instance.OnStrikeLeft;
                @StrikeLeft.canceled += instance.OnStrikeLeft;
                @JumpLeft.started += instance.OnJumpLeft;
                @JumpLeft.performed += instance.OnJumpLeft;
                @JumpLeft.canceled += instance.OnJumpLeft;
                @MoveLeft.started += instance.OnMoveLeft;
                @MoveLeft.performed += instance.OnMoveLeft;
                @MoveLeft.canceled += instance.OnMoveLeft;
            }
        }
    }
    public AllP2Actions @AllP2 => new AllP2Actions(this);
    private int m_XboxControllerSchemeIndex = -1;
    public InputControlScheme XboxControllerScheme
    {
        get
        {
            if (m_XboxControllerSchemeIndex == -1) m_XboxControllerSchemeIndex = asset.FindControlSchemeIndex("Xbox Controller");
            return asset.controlSchemes[m_XboxControllerSchemeIndex];
        }
    }
    public interface ILeftActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnStrike(InputAction.CallbackContext context);
        void OnClawSwap(InputAction.CallbackContext context);
    }
    public interface IRightActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnStrike(InputAction.CallbackContext context);
        void OnClawSwap(InputAction.CallbackContext context);
    }
    public interface IAllP1Actions
    {
        void OnClawSwapRight(InputAction.CallbackContext context);
        void OnClawSwapLeft(InputAction.CallbackContext context);
        void OnStrikeLeft(InputAction.CallbackContext context);
        void OnJumpLeft(InputAction.CallbackContext context);
        void OnMoveLeft(InputAction.CallbackContext context);
        void OnStrikeRight(InputAction.CallbackContext context);
        void OnJumpRight(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
    }
    public interface IAllP2Actions
    {
        void OnClawSwapLeft(InputAction.CallbackContext context);
        void OnClawSwapRight(InputAction.CallbackContext context);
        void OnStrikeRight(InputAction.CallbackContext context);
        void OnJumpRight(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
        void OnStrikeLeft(InputAction.CallbackContext context);
        void OnJumpLeft(InputAction.CallbackContext context);
        void OnMoveLeft(InputAction.CallbackContext context);
    }
}
